WCS\CoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pilot:
            type: string
            length: 255
        freeSeats:
            type: integer
            nullable: true
        takeofTime:
            type: datetime
    lifecycleCallbacks: {  }

    manyToOne:
        departure:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            inversedBy: departures
        arrival:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            inversedBy: arrivals
        model:
            targetEntity: WCS\CoavBundle\Entity\PlaneModel
            inversedBy: models

    oneToMany:
        flight:
            targetEntity: WCS\CoavBundle\Entity\Reservation
            mappedBy: flights

