WCS\CoavBundle\Entity\PlaneModel:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\PlaneModelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        manufacturer:
            type: string
            length: 255
            nullable: true
        cruiseSpeed:
            type: integer
            nullable: true
        nbSeats:
            type: integer
            nullable: true
        status:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    oneToMany:
        models:
          targetEntity: WCS\CoavBundle\Entity\Flight
          mappedBy: model
